import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import { Lexend_Deca } from 'next/font/google'
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900' ]
})
const quicksand = Lexend_Deca({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App", 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className} bg-[#1a1919] text-[#ededed]`} >{children}</body>
    </html>
  );
}
